# Generated by Django 5.2.15 on 2026-09-09 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('branches', models.JSONField(default=list)),
                ('content', models.JSONField(default=dict)),
                ('bac_references', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.CharField(max_length=120)),
                ('verb', models.CharField(max_length=24)),
                ('text', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('rubric', models.JSONField(default=list)),
                ('model_answer', models.TextField()),
                ('source_snapshot', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memory_practice.memorylesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('answer', models.TextField()),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('lease_token', models.CharField(default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='memory_practice.memoryquestion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='memoryquestion',
            constraint=models.UniqueConstraint(fields=('user', 'lesson', 'fingerprint'), name='memory_unique_user_question'),
        ),
        migrations.AddConstraint(
            model_name='memoryattempt',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'request_key'), name='memory_attempt_request_unique'),
        ),
    ]
