# Generated by Django 5.2.15 on 2026-09-11 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.PositiveIntegerField(db_index=True)),
                ('branch_code', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('question_ids', models.JSONField(default=list)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('request_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='memory_exercise_request_unique')],
            },
        ),
    ]
