# Generated by Django 5.2.15 on 2026-07-23 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0009_alter_question_options_question_graph_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=180, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('direction', models.CharField(default='rtl', max_length=10)),
                ('math_format', models.CharField(default='LaTeX', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('generated', 'تم التوليد'), ('reviewed', 'تمت المراجعة'), ('published', 'منشور'), ('published_ready', 'جاهز للنشر')], db_index=True, default='draft', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('imported_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='course.axis')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_axis_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملخص مراجعة المحور',
                'verbose_name_plural': 'ملخصات مراجعة المحاور',
                'ordering': ['order', 'id'],
            },
        ),
    ]
