# Generated by Django 5.2.15 on 2026-09-11 17:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_student_is_active'),
        ('course', '0012_studentquestionsimplesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_type', models.CharField(choices=[('chapter', 'Chapter'), ('subject', 'Subject')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('price_dzd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_packs', to='course.chapter')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_packs', to='course.subject')),
            ],
            options={
                'ordering': ['pack_type', 'price_dzd'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_dzd', models.PositiveIntegerField()),
                ('currency', models.CharField(default='dzd', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('error', 'Error'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('chargily_checkout_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=1000)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('provider_error', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='payments.pack')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_accesses', to='course.chapter')),
                ('source_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='payments.purchase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_accesses', to='accounts.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_accesses', to='course.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chapter__isnull', False), ('pack_type', 'chapter'), ('subject__isnull', True)), models.Q(('chapter__isnull', True), ('pack_type', 'subject'), ('subject__isnull', False)), _connector='OR'), name='pack_has_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('pack_type', 'chapter')), fields=('chapter',), name='unique_pack_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='pack',
            constraint=models.UniqueConstraint(condition=models.Q(('pack_type', 'subject')), fields=('subject',), name='unique_pack_per_subject'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['student', 'status'], name='purchase_student_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'pack'), name='one_pending_purchase_per_pack'),
        ),
        migrations.AddConstraint(
            model_name='studentaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chapter__isnull', True), ('subject__isnull', False)), models.Q(('chapter__isnull', False), ('subject__isnull', True)), _connector='OR'), name='access_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='studentaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('student', 'subject'), name='unique_student_subject_access'),
        ),
        migrations.AddConstraint(
            model_name='studentaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter__isnull', False)), fields=('student', 'chapter'), name='unique_student_chapter_access'),
        ),
    ]
