# Generated by Django 5.2.15 on 2026-09-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_is_active'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['pack_type', 'price_dzd', 'id']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='chargily_customer_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='ChargilyCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], db_index=True, max_length=10)),
                ('customer_id', models.CharField(max_length=150)),
                ('email_snapshot', models.EmailField(blank=True, default='', max_length=254)),
                ('name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargily_customer_links', to='accounts.student')),
            ],
            options={
                'ordering': ['student_id', 'environment'],
                'constraints': [models.UniqueConstraint(fields=('student', 'environment'), name='unique_student_chargily_environment'), models.UniqueConstraint(fields=('environment', 'customer_id'), name='unique_chargily_customer_per_environment')],
            },
        ),
    ]
