# Generated by Django 5.2.15 on 2026-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Code unique')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Année du baccalauréat')),
                ('exercise_number', models.PositiveSmallIntegerField(verbose_name="Numéro de l'exercice")),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Page source')),
                ('axis_tags', models.JSONField(blank=True, default=list, help_text="Liste des axes pédagogiques liés à l'exercice.", verbose_name='Tags des axes')),
                ('content', models.JSONField(default=dict, help_text="Contient le texte de l'exercice, les questions, les solutions, les tableaux et les graphiques.", verbose_name='Contenu complet')),
                ('source_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Fichier JSON source')),
                ('schema_version', models.CharField(blank=True, default='1.0', max_length=30, verbose_name='Version du schéma JSON')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='Langue')),
                ('direction', models.CharField(default='rtl', max_length=10, verbose_name='Direction du texte')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercice du baccalauréat',
                'verbose_name_plural': 'Exercices du baccalauréat',
                'db_table': 'exercise_bac',
                'ordering': ['year', 'exercise_number'],
                'indexes': [models.Index(fields=['year', 'exercise_number'], name='bac_year_number_idx'), models.Index(fields=['is_active', 'year'], name='bac_active_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'exercise_number'), name='unique_bac_exercise_year_number')],
            },
        ),
    ]
