# Generated by Django 5.2.15 on 2026-07-16 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_reexplainstephistory_axis'),
        ('exercise_bac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisebac',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_exerice_bac', to='course.chapter'),
        ),
    ]
