# Generated by Django 5.2.15 on 2026-07-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercise_bac', '0002_exercisebac_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacStepReExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(db_index=True, max_length=150, verbose_name='Identifiant de la question')),
                ('step_number', models.PositiveIntegerField(db_index=True, verbose_name="Numéro de l'étape")),
                ('step_title', models.CharField(blank=True, default='', max_length=255, verbose_name="Titre de l'étape")),
                ('request_type', models.CharField(choices=[('very_simple', 'شرح مبسط جدًا')], default='very_simple', max_length=30, verbose_name='Type de demande')),
                ('explanation', models.JSONField(default=dict, verbose_name='Réexplication générée')),
                ('model', models.CharField(blank=True, default='', max_length=150, verbose_name='Modèle IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_reexplanations', to='exercise_bac.exercisebac', verbose_name='Exercice du baccalauréat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_step_reexplanations', to='accounts.student', verbose_name='Étudiant')),
            ],
        ),
    ]
