# Generated by Django 5.2.15 on 2026-07-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_alter_student_options_student_is_active_and_more'),
        ('course', '0009_alter_question_options_question_graph_data'),
        ('exercise_bac', '0003_bacstepreexplanation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisebac',
            name='unique_bac_exercise_year_number',
        ),
        migrations.AddField(
            model_name='exercisebac',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Filières concernées par cet exercice. Un même exercice peut appartenir à plusieurs filières.', related_name='bac_exercises', to='accounts.branch', verbose_name='Filières'),
        ),
        migrations.AlterField(
            model_name='exercisebac',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_exercises_bac', to='course.chapter', verbose_name='Chapitre'),
        ),
        migrations.AddConstraint(
            model_name='exercisebac',
            constraint=models.UniqueConstraint(fields=('year', 'exercise_number', 'code'), name='unique_bac_exercise_year_number_code'),
        ),
    ]
