# Generated by Django 5.2.15 on 2026-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_alter_student_options_student_is_active_and_more'),
        ('course', '0009_alter_question_options_question_graph_data'),
        ('exercise_bac', '0004_remove_exercisebac_unique_bac_exercise_year_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bacstepreexplanation',
            options={'ordering': ['-created_at'], 'verbose_name': "Réexplication d'une étape", 'verbose_name_plural': 'Réexplications des étapes'},
        ),
        migrations.AlterModelOptions(
            name='exercisebac',
            options={'ordering': ['-year', 'exercise_number', 'id'], 'verbose_name': 'Exercice du baccalauréat', 'verbose_name_plural': 'Exercices du baccalauréat'},
        ),
        migrations.RemoveConstraint(
            model_name='exercisebac',
            name='unique_bac_exercise_year_number_code',
        ),
        migrations.AlterField(
            model_name='bacstepreexplanation',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, verbose_name='Réexplication générée'),
        ),
        migrations.AlterField(
            model_name='exercisebac',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Contient le texte, les questions, les solutions, les tableaux et les graphiques.', verbose_name='Contenu complet'),
        ),
        migrations.AddIndex(
            model_name='bacstepreexplanation',
            index=models.Index(fields=['student', 'exercise', 'question_id', 'step_number'], name='bac_reexp_student_step_idx'),
        ),
        migrations.AddIndex(
            model_name='bacstepreexplanation',
            index=models.Index(fields=['exercise', 'question_id', 'step_number'], name='bac_reexp_exercise_step_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisebac',
            index=models.Index(fields=['chapter', 'is_active', 'year'], name='bac_chapter_active_year_idx'),
        ),
        migrations.AlterModelTable(
            name='bacstepreexplanation',
            table='bac_step_reexplanation',
        ),
    ]
