# Generated by Django 5.2.15 on 2026-08-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_bac', '0005_alter_bacstepreexplanation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisebac',
            name='code',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Code unique'),
        ),
    ]
