# Generated by Django 5.2.15 on 2026-07-12 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('course', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('lesson', 'Lesson'), ('bac_question', 'BAC Question'), ('method', 'Method'), ('concept', 'Concept'), ('theorem', 'Theorem'), ('definition', 'Definition'), ('formula', 'Formula'), ('example', 'Example'), ('skill', 'Skill'), ('roadmap', 'Roadmap'), ('hint', 'Hint'), ('mistake', 'Mistake')], max_length=50)),
                ('subject', models.CharField(default='math', max_length=100)),
                ('branch', models.CharField(default='science', max_length=100)),
                ('chapter', models.CharField(default='sequences', max_length=100)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_page', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('exercise_title', models.CharField(blank=True, max_length=100)),
                ('question_number', models.CharField(blank=True, max_length=50)),
                ('points', models.CharField(blank=True, max_length=50)),
                ('images', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='course.axis')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_name', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('dimension', models.IntegerField(default=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='knowledge.knowledgeitem')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('HAS_SKILL', 'Has Skill'), ('USES_METHOD', 'Uses Method'), ('USES_FORMULA', 'Uses Formula'), ('SUPPORTED_BY', 'Supported By'), ('HAS_EXAMPLE', 'Has Example'), ('HAS_HINT', 'Has Hint'), ('COMMON_MISTAKE', 'Common Mistake'), ('REQUIRES', 'Requires'), ('RELATED_TO', 'Related To'), ('BELONGS_TO_CONCEPT', 'Belongs To Concept')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge.knowledgeitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge.knowledgeitem')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('current_chapter', models.CharField(default='sequences', max_length=100)),
                ('current_axis_tag', models.CharField(blank=True, max_length=100)),
                ('current_skill', models.CharField(blank=True, max_length=100)),
                ('current_intent', models.CharField(blank=True, max_length=100)),
                ('last_question', models.TextField(blank=True)),
                ('last_answer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge.studentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['item_type'], name='knowledge_k_item_ty_c6912b_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['subject', 'branch', 'chapter'], name='knowledge_k_subject_c6dbc7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['year'], name='knowledge_k_year_6adfa4_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['question_number'], name='knowledge_k_questio_0fb4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelationship',
            index=models.Index(fields=['relation_type'], name='knowledge_k_relatio_857679_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgerelationship',
            unique_together={('source', 'target', 'relation_type')},
        ),
    ]
