# Generated by Django 5.2.15 on 2026-07-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        # نحذف الجداول التابعة أولًا
        migrations.DeleteModel(
            name="KnowledgeEmbedding",
        ),

        migrations.DeleteModel(
            name="KnowledgeRelationship",
        ),

        # ثم نحذف الجدول الرئيسي
        migrations.DeleteModel(
            name="KnowledgeItem",
        ),
    ]