# Generated by Django 5.2.15 on 2026-07-17 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0006_subject_category_subject_icon_subject_path_and_more'),
        ('knowledge', '0002_remove_knowledgeitem_axis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Message étudiant', 'verbose_name_plural': 'Messages étudiants'},
        ),
        migrations.AlterModelOptions(
            name='studentsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Session étudiant', 'verbose_name_plural': 'Sessions étudiants'},
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='current_axis_tag',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='current_chapter',
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_messages', to='course.axis', verbose_name='Axe du message'),
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_messages', to='course.chapter', verbose_name='Chapitre du message'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_sessions', to='course.chapter', verbose_name='Chapitre actuel'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='current_axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_sessions', to='course.axis', verbose_name='Axe actuel'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Session active'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Intention'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge.studentsession', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='current_intent',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Intention actuelle'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='current_skill',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Compétence actuelle'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='last_answer',
            field=models.TextField(blank=True, default='', verbose_name='Dernière réponse'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='last_question',
            field=models.TextField(blank=True, default='', verbose_name='Dernière question'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to='accounts.student', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre de la session'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddIndex(
            model_name='studentmessage',
            index=models.Index(fields=['session', 'created_at'], name='message_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmessage',
            index=models.Index(fields=['session', 'role'], name='message_session_role_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmessage',
            index=models.Index(fields=['chapter', 'axis'], name='message_chapter_axis_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmessage',
            index=models.Index(fields=['intent', 'mode'], name='message_intent_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['student', 'is_active'], name='session_student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['student', 'chapter'], name='session_student_chapter_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['chapter', 'current_axis'], name='session_chapter_axis_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsession',
            index=models.Index(fields=['-updated_at'], name='session_updated_idx'),
        ),
    ]
