# Generated by Django 5.2.15 on 2026-07-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_studentmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentsession',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='studentmessage',
            name='message_session_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentmessage',
            name='message_session_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentmessage',
            name='message_chapter_axis_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentmessage',
            name='message_intent_mode_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentsession',
            name='session_student_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentsession',
            name='session_student_chapter_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentsession',
            name='session_chapter_axis_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentsession',
            name='session_updated_idx',
        ),
    ]
