# Generated by Django 5.2.15 on 2026-07-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=180)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('exercise', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('bac', 'تمرين بكالوريا'), ('guided', 'تمرين موجه'), ('practice', 'تمرين تطبيقي'), ('quiz', 'اختبار قصير')], default='bac', max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=20)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('secondary_tags', models.JSONField(blank=True, default=list)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_standalone', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.axis')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='course.branch')),
            ],
            options={
                'ordering': ['axis', 'year', 'order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.TextField(blank=True)),
                ('detailed_explanation', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('final_answer', models.TextField(blank=True)),
                ('verification', models.TextField(blank=True)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('alternative_method', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='course.question')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['axis', 'is_active'], name='question_axis_active_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['axis', 'year'], name='question_axis_year_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['year'], name='question_year_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='question_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='question_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('axis', 'code'), name='unique_question_code_per_axis'),
        ),
        migrations.AddIndex(
            model_name='questionsolution',
            index=models.Index(fields=['is_complete'], name='solution_complete_idx'),
        ),
    ]
