# Generated by Django 5.2.15 on 2026-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_question_questionsolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsolution',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_question_code_per_axis',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_axis_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_axis_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_difficulty_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_type_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='question',
            name='original_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='standalone_support',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='standalone_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='exercise',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='QuestionSolution',
        ),
    ]
