# Generated by Django 5.2.15 on 2026-07-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('course', '0003_remove_questionsolution_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReExplainStepHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(db_index=True, max_length=150)),
                ('step_title', models.CharField(max_length=255)),
                ('step_type', models.CharField(blank=True, default='', max_length=100)),
                ('step_data', models.JSONField(default=dict)),
                ('student_question', models.TextField()),
                ('answer', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_explain_step_history', to='accounts.student')),
            ],
            options={
                'db_table': 're_explain_step_history',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'step_id'], name='student_step_rexp_idx')],
            },
        ),
    ]
