# Generated by Django 5.2.15 on 2026-07-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_reexplainstephistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reexplainstephistory',
            name='axis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='re_explain_step_history', to='course.axis'),
            preserve_default=False,
        ),
    ]
