# Generated by Django 5.2.15 on 2026-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_reexplainstephistory_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(default='science', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='Calculator', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='path',
            field=models.CharField(default='/cour', max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='theme',
            field=models.CharField(default='purple', max_length=30),
        ),
    ]
