# Generated by Django 5.2.15 on 2026-07-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_subject_category_subject_icon_subject_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='path',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='progress',
        ),
    ]
