# Generated by Django 5.2.15 on 2026-07-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_alter_student_options_student_is_active_and_more'),
        ('course', '0007_remove_subject_category_remove_subject_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='accounts.branch'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
