# Generated by Django 5.2.15 on 2026-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_question_branch_alter_subject_branches_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'year', 'exercise', 'number']},
        ),
        migrations.AddField(
            model_name='question',
            name='graph_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
