# Generated by Django 5.2.15 on 2026-07-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_alter_student_options_student_is_active_and_more'),
        ('course', '0009_alter_question_options_question_graph_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='axis',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='axes', to='accounts.branch'),
        ),
    ]
