# Generated by Django 5.2.15 on 2026-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_axis_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
