# Generated by Django 5.2.15 on 2026-08-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_username'),
        ('course', '0011_alter_axis_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestionSimpleSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_simple_solutions', to='course.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_simple_solutions', to='accounts.student')),
            ],
            options={
                'db_table': 'student_question_simple_solutions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student', 'question'], name='stud_q_simple_sol_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'question'), name='unique_student_question_simple_solution')],
            },
        ),
    ]
