# Generated by Django 5.2.15 on 2026-08-13 12:12

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0012_studentquestionsimplesolution'),
        ('tutor', '0001_enable_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('lesson', 'Lesson'), ('question', 'Question'), ('solution', 'Solution'), ('bac_exercise', 'Bac Exercise')], db_index=True, max_length=30)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('chunk_key', models.CharField(db_index=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_chunks', to='course.axis')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='course.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='course.subject')),
            ],
            options={
                'db_table': 'tutor_rag_chunk',
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'chunk_key'), name='unique_tutor_rag_chunk')],
            },
        ),
    ]
