# Generated by Django 5.2.15 on 2026-08-13 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_is_active'),
        ('course', '0012_studentquestionsimplesolution'),
        ('tutor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_chat_sessions', to='course.axis')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_chat_sessions', to='course.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chat_sessions', to='accounts.student')),
            ],
            options={
                'db_table': 'tutor_chat_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor.tutorchatsession')),
            ],
            options={
                'db_table': 'tutor_chat_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tutorchatsession',
            index=models.Index(fields=['student', 'is_active', 'updated_at'], name='tutor_session_student_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='tutor_message_session_idx'),
        ),
    ]
