# Generated by Django 5.2.15 on 2026-07-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_reexplainstephistory_axis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=20)),
                ('exercise_type', models.CharField(default='application', max_length=100)),
                ('skill', models.CharField(blank=True, default='', max_length=255)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('common_mistake', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to='course.axis')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
