# Generated by Django 5.2.15 on 2026-09-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_student_is_active'),
        ('course', '0012_studentquestionsimplesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=20)),
                ('exercise_type', models.CharField(default='application', max_length=100)),
                ('skill', models.CharField(blank=True, default='', max_length=255)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('common_mistake', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_graph', models.BooleanField(default=False)),
                ('graph_data', models.JSONField(blank=True, default=dict)),
                ('verification', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to='course.axis')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercises', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedExerciseAlternativeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, default='')),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_solutions', to='exercise_generation.generatedexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercise_alternative_solutions', to='accounts.student')),
            ],
            options={
                'verbose_name': 'حل بديل مبسط',
                'verbose_name_plural': 'الحلول البديلة المبسطة',
                'ordering': ['-created_at'],
            },
        ),
    ]
