# Generated by Django 5.2.15 on 2026-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedexercise',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات التوليد'),
        ),
    ]
