# Generated by Django 5.2.15 on 2026-07-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exercise_generation', '0002_alter_generatedexercise_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExerciseAlternativeSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, default='')),
                ('solution_steps', models.JSONField(blank=True, default=list)),
                ('final_answer', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_solutions', to='exercise_generation.generatedexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exercise_alternative_solutions', to='accounts.student')),
            ],
            options={
                'verbose_name': 'حل بديل مبسط',
                'verbose_name_plural': 'الحلول البديلة المبسطة',
                'ordering': ['-created_at'],
            },
        ),
    ]
