# Generated by Django 5.2.15 on 2026-07-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_generation', '0004_generatedexercisealternativesolution_graph_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedexercisealternativesolution',
            name='graph_data',
        ),
        migrations.RemoveField(
            model_name='generatedexercisealternativesolution',
            name='requires_graph',
        ),
        migrations.RemoveField(
            model_name='generatedexercisealternativesolution',
            name='verification',
        ),
        migrations.AddField(
            model_name='generatedexercise',
            name='graph_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedexercise',
            name='requires_graph',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedexercise',
            name='verification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
