# Generated by Django 5.2.15 on 2026-08-26 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_student_is_active'),
        ('course', '0012_studentquestionsimplesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('current_section', models.CharField(blank=True, default='', max_length=100)),
                ('current_exercise_kind', models.CharField(blank=True, default='', max_length=80)),
                ('current_exercise_id', models.CharField(blank=True, default='', max_length=120)),
                ('current_exercise_title', models.CharField(blank=True, default='', max_length=255)),
                ('current_step_id', models.CharField(blank=True, default='', max_length=150)),
                ('current_skill', models.CharField(blank=True, default='', max_length=150)),
                ('current_intent', models.CharField(blank=True, default='', max_length=100)),
                ('last_question', models.TextField(blank=True, default='')),
                ('last_answer', models.TextField(blank=True, default='')),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_tutor_sessions', to='course.chapter')),
                ('current_axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextual_tutor_sessions', to='course.axis')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextual_tutor_sessions', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=100)),
                ('mode', models.CharField(blank=True, default='', max_length=100)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextual_tutor_messages', to='course.axis')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextual_tutor_messages', to='course.chapter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor_chat.studentsession')),
            ],
        ),
    ]
