# Generated by Django 5.2.15 on 2026-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='current_question_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='current_question_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='current_question_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='current_step_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='current_step_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
