# Generated by Django 5.2.15 on 2026-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_alter_student_options_student_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
