# Generated by Django 5.2.15 on 2026-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_email_verified_at_alter_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
