# Generated by Django 5.2.15 on 2026-07-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_branch_alter_student_options_student_is_active_and_more'),
        ('course', '0009_alter_question_options_question_graph_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBacExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التمرين')),
                ('exercise', models.JSONField(default=dict, help_text='يحتوي نص التمرين والأسئلة دون الحل.', verbose_name='التمرين المولد')),
                ('solution', models.JSONField(blank=True, default=dict, help_text='يُنشأ فقط عندما يطلبه الطالب.', verbose_name='الحل المفصل')),
                ('reference_exercise_ids', models.JSONField(blank=True, default=list, verbose_name='معرفات تمارين البكالوريا المرجعية')),
                ('selection_strategy', models.CharField(default='diverse_random', max_length=30, verbose_name='طريقة اختيار المراجع')),
                ('model_exercise', models.CharField(blank=True, default='', max_length=150)),
                ('model_solution', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('exercise_ready', 'التمرين جاهز'), ('solution_ready', 'الحل جاهز'), ('failed', 'فشل التوليد')], db_index=True, default='exercise_ready', max_length=30)),
                ('generation_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_bac_exercises', to='accounts.branch', verbose_name='الشعبة')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_bac_exercises', to='course.chapter', verbose_name='الوحدة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_bac_exercises', to='accounts.student', verbose_name='الطالب')),
            ],
            options={
                'db_table': 'generated_bac_exercise',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'chapter', 'branch', 'created_at'], name='gen_bac_student_filter_idx'), models.Index(fields=['chapter', 'branch', 'status'], name='gen_bac_chapter_branch_idx')],
            },
        ),
    ]
