# Generated by Django 5.2.15 on 2026-08-09 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_username'),
        ('generated_bac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBacQuestionReExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(db_index=True, max_length=80, verbose_name='معرف السؤال')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='رقم إعادة الشرح')),
                ('explanation', models.JSONField(default=dict, verbose_name='إعادة الشرح')),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_explanations', to='generated_bac.generatedbacexercise', verbose_name='التمرين المولد')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_bac_re_explanations', to='accounts.student', verbose_name='الطالب')),
            ],
            options={
                'db_table': 'generated_bac_question_re_explanation',
                'ordering': ['question_id', 'attempt_number', 'created_at'],
                'indexes': [models.Index(fields=['student', 'generated_exercise', 'question_id'], name='gen_bac_reexp_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('generated_exercise', 'question_id', 'attempt_number'), name='uniq_gen_bac_reexp_attempt')],
            },
        ),
    ]
