# Generated by Django 5.2.15 on 2026-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generated_bac', '0002_generatedbacquestionreexplanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedbacexercise',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات التوليد'),
        ),
    ]
