# Generated by Django 5.2.15 on 2026-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generated_bac', '0003_generatedbacexercise_generation_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedbacexercise',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
