# Generated by Django 5.2.15 on 2026-08-18 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_student_is_active'),
        ('course', '0012_studentquestionsimplesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('full', 'Full axis assessment'), ('remedial', 'Weak-points retest')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('blueprint', models.JSONField(blank=True, default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('mastery_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_tests', to='course.axis')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_tests', to='accounts.branch')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_tests', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BacIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('frequency_level', models.CharField(choices=[('very_high', 'Very high'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('rare', 'Rare')], default='medium', max_length=20)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('years', models.JSONField(blank=True, default=list)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('external_prerequisites', models.JSONField(blank=True, default=list)),
                ('difficulty_min', models.PositiveSmallIntegerField(default=1)),
                ('difficulty_max', models.PositiveSmallIntegerField(default=3)),
                ('bac_occurrences', models.JSONField(blank=True, default=list)),
                ('mastery_requirements', models.JSONField(blank=True, default=dict)),
                ('generation_guidance', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_ideas', to='course.axis')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_ideas', to='accounts.branch')),
            ],
            options={
                'ordering': ['axis_id', 'branch_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BacIdeaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('years', models.JSONField(blank=True, default=list)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('distinguishing_feature', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('bac_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adaptive_assessment.bacidea')),
            ],
            options={
                'ordering': ['bac_idea_id', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ideas', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_skills', to='course.axis')),
            ],
            options={
                'ordering': ['axis_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Misconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('related_skill_idea_codes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='course.axis')),
                ('bac_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='adaptive_assessment.bacidea')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='adaptive_assessment.skill')),
            ],
            options={
                'ordering': ['axis_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('bac', 'BAC idea'), ('skill', 'Lesson skill')], max_length=20)),
                ('target_skill_idea_codes', models.JSONField(blank=True, default=list)),
                ('target_misconception_codes', models.JSONField(blank=True, default=list)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('question', models.JSONField(default=dict)),
                ('generation_model', models.CharField(blank=True, default='', max_length=120)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('is_validated', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='adaptive_assessment.adaptivetest')),
                ('bac_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_questions', to='adaptive_assessment.bacidea')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_questions', to='adaptive_assessment.bacideavariant')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_questions', to='adaptive_assessment.skill')),
            ],
            options={
                'ordering': ['test_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentBacIdeaMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('mastered_variant_codes', models.JSONField(blank=True, default=list)),
                ('weak_variant_codes', models.JSONField(blank=True, default=list)),
                ('detected_misconception_codes', models.JSONField(blank=True, default=list)),
                ('is_mastered', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('bac_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_masteries', to='adaptive_assessment.bacidea')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bac_idea_masteries', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('mastered_idea_codes', models.JSONField(blank=True, default=list)),
                ('weak_idea_codes', models.JSONField(blank=True, default=list)),
                ('is_mastered', models.BooleanField(default=False)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_masteries', to='adaptive_assessment.skill')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('detected_misconception_codes', models.JSONField(blank=True, default=list)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('solution_viewed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_answers', to='accounts.student')),
                ('test_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='adaptive_assessment.adaptivetestquestion')),
            ],
            options={
                'ordering': ['test_question__test_id', 'test_question__order'],
                'indexes': [models.Index(fields=['student', 'is_correct'], name='adaptive_as_student_a3ce3f_idx'), models.Index(fields=['created_at'], name='adaptive_as_created_d6f919_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bacidea',
            index=models.Index(fields=['axis', 'branch', 'is_active'], name='adaptive_as_axis_id_2fbde2_idx'),
        ),
        migrations.AddIndex(
            model_name='bacidea',
            index=models.Index(fields=['priority', 'frequency_level'], name='adaptive_as_priorit_4710ef_idx'),
        ),
        migrations.AddIndex(
            model_name='bacidea',
            index=models.Index(fields=['code'], name='adaptive_as_code_3b5beb_idx'),
        ),
        migrations.AddConstraint(
            model_name='bacidea',
            constraint=models.UniqueConstraint(fields=('axis', 'branch', 'code'), name='adaptive_unique_bac_idea_axis_branch_code'),
        ),
        migrations.AddIndex(
            model_name='bacideavariant',
            index=models.Index(fields=['bac_idea', 'is_active'], name='adaptive_as_bac_ide_7fa90c_idx'),
        ),
        migrations.AddIndex(
            model_name='bacideavariant',
            index=models.Index(fields=['code'], name='adaptive_as_code_0d4ff4_idx'),
        ),
        migrations.AddConstraint(
            model_name='bacideavariant',
            constraint=models.UniqueConstraint(fields=('bac_idea', 'code'), name='adaptive_unique_variant_code_per_bac_idea'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['axis', 'is_active'], name='adaptive_as_axis_id_38aa9c_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['code'], name='adaptive_as_code_759f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('axis', 'code'), name='adaptive_unique_skill_code_per_axis'),
        ),
        migrations.AddIndex(
            model_name='misconception',
            index=models.Index(fields=['axis', 'is_active'], name='adaptive_as_axis_id_f13d15_idx'),
        ),
        migrations.AddIndex(
            model_name='misconception',
            index=models.Index(fields=['code'], name='adaptive_as_code_078348_idx'),
        ),
        migrations.AddConstraint(
            model_name='misconception',
            constraint=models.UniqueConstraint(fields=('axis', 'code'), name='adaptive_unique_misconception_code_per_axis'),
        ),
        migrations.AddIndex(
            model_name='adaptivetestquestion',
            index=models.Index(fields=['test', 'order'], name='adaptive_as_test_id_92452e_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivetestquestion',
            index=models.Index(fields=['bac_idea', 'variant'], name='adaptive_as_bac_ide_4f25a8_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivetestquestion',
            index=models.Index(fields=['skill'], name='adaptive_as_skill_i_2afbd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='adaptivetestquestion',
            constraint=models.UniqueConstraint(fields=('test', 'order'), name='adaptive_unique_question_order_per_test'),
        ),
        migrations.AddIndex(
            model_name='studentbacideamastery',
            index=models.Index(fields=['student', 'is_mastered'], name='adaptive_as_student_c63216_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbacideamastery',
            index=models.Index(fields=['bac_idea', 'mastery_score'], name='adaptive_as_bac_ide_858458_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentbacideamastery',
            constraint=models.UniqueConstraint(fields=('student', 'bac_idea'), name='adaptive_unique_student_bac_idea_mastery'),
        ),
        migrations.AddIndex(
            model_name='studentskillmastery',
            index=models.Index(fields=['student', 'is_mastered'], name='adaptive_as_student_99e4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentskillmastery',
            index=models.Index(fields=['skill', 'mastery_score'], name='adaptive_as_skill_i_54e650_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentskillmastery',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='adaptive_unique_student_skill_mastery'),
        ),
    ]
